// packages/core/src/components/FormComponentWrapper.tsx
import * as React from "react";
import { WidgetProps } from "../widget";
import FormElement from "./FormElement";

/**
 * A general purpose component wrapper. This component can be used to make sure
 * all widgets renders form elements in a similar way.
 * @group React API
 */
export default function FormComponentWrapper(
  props: Omit<WidgetProps<any, any>, "onChange"> & {
    /**
     * The actual form widget contents.
     */
    children: React.ReactNode;
    /**
     * The id that should be applied to the form element.
     */
    id?: string;
    /**
     * The label for the form element.
     */
    label?: string;
    /**
     * Any prefix that should be rendered before the actual form element.
     */
    prefix?: string;
  },
): JSX.Element {
  const component = props.component;
  const classes = props.theme.classes;
  return (
    <FormElement
      id={props.id ? props.id : props.name}
      label={!props.hideLabel ? props.label ?? component.label : undefined}
      childrenClass={
        props.prefix ? classes.prefixedElementWrapper : classes.elementWrapper
      }
      required={component.required}
      requiredText={props.labels?.required ?? "Required"}
      requiredClass={classes.requiredIndicator}
      labelClass={classes.label}
      labelWrapperClass={classes.labelWrapper}
    >
      {props.prefix && (
        <div className={classes.inputPrefixWrapper}>
          <div className={classes.inputPrefix}>{props.prefix}</div>
        </div>
      )}
      {props.children}
    </FormElement>
  );
}

// packages/svelte/src/lib/components/FormComponentWrapper.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { WidgetProps } from "@fab4m/fab4m";
  import FormElement from "./FormElement.svelte";

  type Props = Partial<Omit<WidgetProps<any, any>, "onChange">> & {
    id?: string;
    label?: string;
    prefix?: string;
    component: WidgetProps<any, any>["component"];
    theme: WidgetProps<any, any>["theme"];
    name: string;
    children: Snippet;
  };

  let {
    component,
    theme,
    hideLabel,
    labels,
    name,
    id,
    label,
    prefix,
    children,
  }: Props = $props();

  const classes = $derived(theme.classes);
  const elementId = $derived(id ? id : name);
  const elementLabel = $derived(
    !hideLabel ? (label ?? component.label) : undefined,
  );
  const childrenClass = $derived(
    prefix ? classes.prefixedElementWrapper : classes.elementWrapper,
  );
</script>

<FormElement
  id={elementId}
  label={elementLabel}
  required={component.required}
  requiredText={labels?.required ?? "Required"}
  requiredClass={classes.requiredIndicator}
  labelClass={classes.label}
  labelWrapperClass={classes.labelWrapper}
  {childrenClass}
>
  {#if prefix}
    <div class={classes.inputPrefixWrapper}>
      <div class={classes.inputPrefix}>{prefix}</div>
    </div>
  {/if}
  {@render children()}
</FormElement>
