// packages/react/src/components/FormView.tsx
import * as React from "react";
import {
  Form,
  formParts,
  FormViewProps,
  getNextPart,
  getPrevPart,
  ValidationError,
} from "@fab4m/fab4m";
import { FormDataContext, FormErrorsContext } from "../context";
import { FormPager } from "./FormPager";
import { FormPart } from "./FormPart";
import { FormWrapper } from "./FormWrapper";

/**
 * This component is used to render any form with the provided data.
 * @group React API
 */
export function FormView(props: FormViewProps): React.JSX.Element {
  const [formErrors, setFormErrors] = initFormErrors(
    props.errors,
    props.errorsChanged,
  );
  const [part, setPart] = React.useState(
    typeof props.part !== "undefined" ? props.part : 0,
  );
  const goBack = () => {
    setPart(part - 1);
  };
  const data = props.data as Record<string, unknown>;
  const parts = formParts(props.form, data);
  const renderedParts =
    typeof props.part !== "undefined" ? (
      <FormPart
        ssr={!!props.ssr}
        form={props.form as Form<Record<string, unknown>>}
        hide={false}
        idPrefix={props.idPrefix}
        errors={formErrors}
        data={data}
        components={parts[part]}
      />
    ) : (
      parts
        .slice(0, part + 1)
        .map((formPart, index) => (
          <FormPart
            ssr={!!props.ssr}
            form={props.form as Form<Record<string, unknown>>}
            key={index}
            idPrefix={props.idPrefix}
            hide={index !== part}
            errors={formErrors}
            data={data}
            components={formPart}
          />
        ))
    );
  return (
    <FormDataContext.Provider value={data}>
      <FormErrorsContext.Provider value={formErrors}>
        <FormWrapper
          {...props}
          parts={parts}
          part={part}
          setPart={setPart}
          ssr={props.ssr}
          className={props.className}
          setFormErrors={setFormErrors}
        >
          {renderedParts}
          <FormPager
            theme={props.form.theme}
            form={props.form}
            part={part}
            disabled={props.disabled}
            hasNextPart={getNextPart(parts, part, data) !== -1}
            hasPrevPart={getPrevPart(parts, part, data) !== -1}
            goBack={goBack}
            noParts={parts.length}
            hideSubmit={props.hideSubmit}
          />
        </FormWrapper>
      </FormErrorsContext.Provider>
    </FormDataContext.Provider>
  );
}

export function initFormErrors(
  errors?: ValidationError[],
  errorsChanged?: (errors: ValidationError[]) => void,
): [ValidationError[], (errors: ValidationError[]) => void] {
  if (errorsChanged) {
    return [errors ?? [], errorsChanged];
  }
  return React.useState(errors ?? []);
}

// packages/svelte/src/lib/components/FormView.svelte
<script lang="ts">
  import {
    Form,
    formParts,
    getNextPart,
    getPrevPart,
  } from "@fab4m/fab4m";
  import type {
    FormViewProps,
    ValidationError,
  } from "@fab4m/fab4m";
  import {
    setFormDataContext,
    setFormErrorsContext,
  } from "../context.js";
  import FormPager from "./FormPager.svelte";
  import FormPart from "./FormPart.svelte";
  import FormWrapper from "./FormWrapper.svelte";

  /**
   * This component is used to render any form with the provided data.
   * @group Svelte API
   */
  type Props = FormViewProps;

  let {
    form,
    data,
    errors,
    errorsChanged,
    part: propsPart,
    ssr,
    idPrefix,
    className,
    disabled,
    hideSubmit,
    extra,
    action,
  }: Props = $props();

  // Initialize form errors state
  // If errorsChanged is provided (controlled mode), use errors from props
  // Otherwise, use internal state
  let internalFormErrors = $state(errors ?? []);
  let formErrors = $derived(
    errorsChanged ? (errors ?? []) : internalFormErrors,
  );
  const setFormErrors = errorsChanged ?? ((e: ValidationError[]) => {
    internalFormErrors = e;
  });

  // Initialize part state
  let part = $state(typeof propsPart !== "undefined" ? propsPart : 0);

  const setPart = (newPart: number) => {
    part = newPart;
  };

  const goBack = () => {
    part = part - 1;
  };

  const formData = $derived(data as Record<string, unknown>);
  const parts = $derived(formParts(form, formData));
  const hasNextPart = $derived(
    getNextPart(parts, part, formData) !== -1,
  );
  const hasPrevPart = $derived(
    getPrevPart(parts, part, formData) !== -1,
  );

  // Set context for child components
  setFormDataContext(formData);
  setFormErrorsContext(formErrors);
</script>

<FormWrapper
  {form}
  data={formData}
  errors={formErrors}
  {parts}
  {part}
  {setPart}
  {ssr}
  {className}
  {setFormErrors}
  {extra}
  {action}
>
  {#if typeof propsPart !== "undefined"}
    <FormPart
      ssr={!!ssr}
      form={form as Form<Record<string, unknown>>}
      hide={false}
      {idPrefix}
      errors={formErrors}
      data={formData}
      components={parts[part]}
    />
  {:else}
    {#each parts.slice(0, part + 1) as formPart, index}
      <FormPart
        ssr={!!ssr}
        form={form as Form<Record<string, unknown>>}
        {idPrefix}
        hide={index !== part}
        errors={formErrors}
        data={formData}
        components={formPart}
      />
    {/each}
  {/if}
  <FormPager
    theme={form.theme}
    {form}
    {part}
    {disabled}
    {hasNextPart}
    {hasPrevPart}
    {goBack}
    noParts={parts.length}
    {hideSubmit}
  />
</FormWrapper>
