// packages/react/src/components/Input.tsx
import * as React from "react";
import { WidgetProps } from "@fab4m/fab4m";
import { FormComponentWrapper } from "./FormComponentWrapper";
/**
 * @internal
 */
export function Input(
  props: WidgetProps<string, { prefix?: string } | undefined> & {
    type: string;
  },
): React.JSX.Element {
  const component = props.component;
  const classes = props.theme.classes;
  return (
    <FormComponentWrapper {...props} prefix={props.settings?.prefix}>
      <input
        type={props.type}
        className={classes.input}
        required={component.required}
        disabled={component.disabled}
        value={props.value ?? ""}
        onChange={(e) => props.onChange(e.currentTarget.value)}
        name={props.name}
        id={props.id}
        {...props.attributes}
      />
    </FormComponentWrapper>
  );
}

// packages/svelte/src/lib/components/Input.svelte
<script lang="ts">
  /**
   * @internal
   */
  import type { WidgetProps } from "@fab4m/fab4m";
  import FormComponentWrapper from "./FormComponentWrapper.svelte";

  type Props = Partial<Pick<WidgetProps<string, any>, "settings" | "ssr">> &
    Omit<WidgetProps<string, { prefix?: string } | undefined>, "settings" | "ssr"> & {
      type: string;
    };

  let {
    component,
    theme,
    settings,
    value,
    onChange,
    name,
    id,
    attributes,
    hideLabel,
    labels,
    type,
  }: Props = $props();

  let classes = $derived(theme.classes);
</script>

<FormComponentWrapper
  {component}
  {theme}
  {hideLabel}
  {labels}
  {name}
  {id}
  prefix={settings?.prefix}
>
  <input
    {type}
    class={classes.input}
    required={component.required}
    disabled={component.disabled}
    value={value ?? ""}
    oninput={(e) => onChange(e.currentTarget.value)}
    {name}
    {id}
    {...attributes}
  />
</FormComponentWrapper>
