// packages/react/src/components/ValidatorInfo.tsx
import * as React from "react";
import { FormComponent, Theme } from "@fab4m/fab4m";
import { useFormRendererContext } from "../formrenderer";
/**
 * Render Validatior information for a specific component.
 * @group React widget API.
 */
export function ValidatorInfo(props: {
  value: unknown;
  component: FormComponent;
  theme: Theme;
}): React.JSX.Element | null {
  const { validatorComponents } = useFormRendererContext();
  if (!validatorComponents) {
    return null;
  }
  const info = [];
  for (const v of props.component.validators) {
    if (validatorComponents[v.type.name]) {
      const Validator = validatorComponents[v.type.name];
      info.push(
        <Validator
          key={info.length}
          theme={props.theme}
          value={props.value}
          settings={v.settings}
        />,
      );
    }
  }
  return info.length > 0 ? <div>{info}</div> : null;
}

// packages/svelte/src/lib/components/ValidatorInfo.svelte
<script lang="ts">
  import type { FormComponent, Theme } from "@fab4m/fab4m";
  import { getFormRendererContext } from "../formrenderer.js";

  let {
    value,
    component,
    theme,
  }: {
    value: unknown;
    component: FormComponent;
    theme: Theme;
  } = $props();

  const { validatorComponents } = getFormRendererContext();
</script>

{#if validatorComponents}
  {@const hasValidators = component.validators.some(
    (v) => validatorComponents[v.type.name],
  )}
  {#if hasValidators}
    <div>
      {#each component.validators as v}
        {#if validatorComponents[v.type.name]}
          {@const Validator = validatorComponents[v.type.name]}
          <Validator {theme} {value} settings={v.settings} />
        {/if}
      {/each}
    </div>
  {/if}
{/if}
