// fab4m.org-astro/src/components/examples/Labels.tsx
import React from "react";
import { createForm, textField } from "@fab4m/fab4m";
import {
  StatefulFormView,
  FormProvider,
  allWidgetsRenderer,
} from "@fab4m/react";

const form = createForm(
  {
    name: textField({
      label: "Your name",
      required: true,
    }),
  },
  { labels: { submit: "Enter your name" } },
);

export default function Labels() {
  form.onSubmit((e) => {
    e.preventDefault();
  });

  return (
    <FormProvider renderer={allWidgetsRenderer}>
      <StatefulFormView form={form} />
    </FormProvider>
  );
}

// fab4m.org-astro/src/components/examples/Labels.svelte
<script lang="ts">
  import { createForm, textField } from "@fab4m/fab4m";
  import {
    StatefulFormView,
    FormProvider,
    allWidgetsRenderer,
  } from "@fab4m/svelte";

  const form = createForm(
    {
      name: textField({
        label: "Your name",
        required: true,
      }),
    },
    { labels: { submit: "Enter your name" } },
  );

  form.onSubmit((e) => {
    e.preventDefault();
  });
</script>

<FormProvider renderer="{allWidgetsRenderer}">
  <StatefulFormView {form} />
</FormProvider>
