// packages/react/src/widgets/DateRangeField.tsx
import * as React from "react";
import { useEffect, useState } from "react";
import { DateRange, DateRangeWidgetSettings, WidgetProps } from "@fab4m/fab4m";
import { FormComponentWrapper } from "../components/FormComponentWrapper";

function toInputValue(value: Date | undefined, withTime: boolean): string {
  if (!value) {
    return "";
  }
  return withTime
    ? value.toISOString().slice(0, 16)
    : value.toISOString().slice(0, 10);
}

/**
 * A native date range widget with two labeled inputs.
 * See [the date component page](/docs/components/date) for an example.
 * @group React widgets
 */
export function DateRangeField(
  props: WidgetProps<DateRange, DateRangeWidgetSettings>,
): React.JSX.Element {
  const [state, changeState] = useState<Partial<DateRange>>(props.value ?? {});
  useEffect(() => {
    if (props.value) {
      changeState(props.value);
    }
  }, [props.value]);

  const withTime = !!props.settings.withTime;
  const type = withTime ? "datetime-local" : "date";
  const classes = props.theme.classes;
  const fromId = `${props.id}_from`;
  const toId = `${props.id}_to`;
  const fromName = `${props.name}[from]`;
  const toName = `${props.name}[to]`;

  const changeFromDate = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.currentTarget.value;
    const from = value ? new Date(value) : undefined;
    const newState = { ...state, from };
    changeState(newState);
    if (newState.from) {
      props.onChange({
        from: newState.from,
        to: newState.to,
      });
    }
  };
  const changeToDate = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.currentTarget.value;
    const to = value ? new Date(value) : undefined;
    const newState = { ...state, to };
    changeState(newState);
    if (state.from) {
      props.onChange({ from: state.from, to });
    }
  };

  return (
    <FormComponentWrapper {...props}>
      <div className={classes.dateRangeWrapper ?? "date-range-wrapper"}>
        <input
          type={type}
          className={classes.input}
          required={props.component.required}
          disabled={props.component.disabled}
          value={toInputValue(state.from, withTime)}
          onChange={changeFromDate}
          name={fromName}
          id={fromId}
          aria-label={props.settings.fromLabel}
          placeholder={props.settings.fromLabel}
          {...props.attributes}
        />
        <div className={classes.dateRangeSeparator ?? "date-range-separator"}>
          -
        </div>
        <input
          type={type}
          className={classes.input}
          required={!props.settings.optionalEndDate && !!state.from}
          disabled={props.component.disabled}
          value={toInputValue(state.to, withTime)}
          onChange={changeToDate}
          name={toName}
          id={toId}
          aria-label={props.settings.toLabel}
          placeholder={props.settings.toLabel}
          {...props.attributes}
        />
      </div>
    </FormComponentWrapper>
  );
}

// packages/svelte/src/lib/widgets/DateRangeField.svelte
<script lang="ts">
  import { untrack } from "svelte";
  import type {
    DateRange,
    DateRangeWidgetSettings,
    WidgetProps,
  } from "@fab4m/fab4m";
  import FormComponentWrapper from "../components/FormComponentWrapper.svelte";

  type Props = WidgetProps<DateRange, DateRangeWidgetSettings>;

  let {
    component,
    theme,
    settings,
    value,
    onChange,
    name,
    id,
    attributes,
    hideLabel,
    labels,
  }: Props = $props();

  let state = $state<Partial<DateRange>>(untrack(() => value ?? {}));

  $effect(() => {
    if (value) {
      state = value;
    }
  });

  const withTime = $derived(!!settings?.withTime);
  const type = $derived(withTime ? "datetime-local" : "date");
  const classes = $derived(theme.classes);
  const fromId = $derived(`${id}_from`);
  const toId = $derived(`${id}_to`);
  const fromName = $derived(`${name}[from]`);
  const toName = $derived(`${name}[to]`);

  function toInputValue(v: Date | undefined): string {
    if (!v) {
      return "";
    }
    return withTime
      ? v.toISOString().slice(0, 16)
      : v.toISOString().slice(0, 10);
  }

  function changeFromDate(e: Event) {
    const target = e.currentTarget as HTMLInputElement;
    const v = target.value;
    const from = v ? new Date(v) : undefined;
    state = { ...state, from };
    if (from) {
      onChange({ from, to: state.to });
    }
  }

  function changeToDate(e: Event) {
    const target = e.currentTarget as HTMLInputElement;
    const v = target.value;
    const to = v ? new Date(v) : undefined;
    state = { ...state, to };
    if (state.from) {
      onChange({ from: state.from, to });
    }
  }
</script>

<FormComponentWrapper
  {component}
  {theme}
  {hideLabel}
  {labels}
  {name}
  {id}
>
  <div class={classes.dateRangeWrapper ?? "date-range-wrapper"}>
    <input
      {type}
      class={classes.input}
      required={component.required}
      disabled={component.disabled}
      value={toInputValue(state.from)}
      oninput={changeFromDate}
      name={fromName}
      id={fromId}
      aria-label={settings?.fromLabel}
      placeholder={settings?.fromLabel}
      {...attributes}
    />
    <div class={classes.dateRangeSeparator ?? "date-range-separator"}>
      -
    </div>
    <input
      {type}
      class={classes.input}
      required={!settings?.optionalEndDate && !!state.from}
      disabled={component.disabled}
      value={toInputValue(state.to)}
      oninput={changeToDate}
      name={toName}
      id={toId}
      aria-label={settings?.toLabel}
      placeholder={settings?.toLabel}
      {...attributes}
    />
  </div>
</FormComponentWrapper>
