// packages/password/src/PasswordValidateOld.tsx
import * as React from "react";
import { WidgetProps, FormElement } from "@fab4m/fab4m";
import { PasswordValidateOldSettings, PasswordValidateOldData } from ".";

/**
 * This widget renders three password input fields: new password,
 * verify new password and old password.
 * @group React widgets
 */
export default function PasswordValidateOld(
  props: WidgetProps<PasswordValidateOldData, PasswordValidateOldSettings>
): JSX.Element {
  const component = props.component;
  const confirmName = `${props.id}_confirm`;
  const confirmTitle = props.settings.confirmTitle
    ? props.settings.confirmTitle
    : "Confirm password";
  const oldPasswordLabel = props.settings.oldPasswordLabel ?? "Old password";
  const classes = props.theme.classes;
  return (
    <>
      <div className={props.theme.classes.componentWrapper}>
        <FormElement
          labelClass={classes.label}
          childrenClass={classes.elementWrapper}
          required={component.required}
          requiredText={props.labels?.required ?? "Required"}
          requiredClass={classes.requiredIndicator}
          labelWrapperClass={classes.labelWrapper}
          id={props.name}
          label={oldPasswordLabel}
        >
          <input
            type="password"
            className={classes.input}
            required={
              component.required ||
              (props.value && props.value.oldPassword.length > 0)
            }
            value={props.value?.oldPassword}
            onChange={(e) =>
              props.onChange({
                ...value(props.value),
                oldPassword: e.currentTarget.value,
              })
            }
            name={`${props.name}[oldpassword]`}
            id={`${props.id}_oldpassword`}
            {...props.attributes}
          />
        </FormElement>
      </div>
      <div className={props.theme.classes.componentWrapper}>
        <FormElement
          labelClass={classes.label}
          childrenClass={classes.elementWrapper}
          required={component.required}
          requiredText={props.labels?.required ?? "Required"}
          requiredClass={classes.requiredIndicator}
          labelWrapperClass={classes.labelWrapper}
          id={props.id}
          label={component.label}
        >
          <input
            type="password"
            className={classes.input}
            required={component.required}
            value={props.value?.password}
            onChange={(e) =>
              props.onChange({
                ...value(props.value),
                password: e.currentTarget.value,
              })
            }
            name={`${props.name}[password]`}
            id={props.id}
            {...props.attributes}
          />
        </FormElement>
      </div>
      <div className={props.theme.classes.componentWrapper}>
        <FormElement
          labelClass={classes.label}
          childrenClass={classes.elementWrapper}
          required={component.required}
          requiredText={props.labels?.required ?? "Required"}
          requiredClass={classes.requiredIndicator}
          labelWrapperClass={classes.labelWrapper}
          id={confirmName}
          label={confirmTitle}
        >
          <input
            type="password"
            className={classes.input}
            required={component.required}
            value={props.value?.confirmPassword}
            onChange={(e) =>
              props.onChange({
                ...value(props.value),
                confirmPassword: e.currentTarget.value,
              })
            }
            name={`${props.name}[confirmPassword]`}
            id={`${props.id}_confirm`}
            pattern={props.value ? `^${props.value.password}$` : undefined}
          />
          {props.value &&
            props.value.password.length > 0 &&
            props.value.confirmPassword === props.value.password && (
              <div className={classes.descriptionOk}>The password matches!</div>
            )}
        </FormElement>
      </div>
    </>
  );
}

const defaultValue: PasswordValidateOldData = {
  password: "",
  oldPassword: "",
  confirmPassword: "",
};

function value(val?: PasswordValidateOldData) {
  return val ?? defaultValue;
}

// packages/svelte/src/lib/widgets/PasswordValidateOld.svelte
<script lang="ts">
  import type {
    PasswordValidateOldData,
    PasswordValidateOldSettings,
    WidgetProps,
  } from "@fab4m/fab4m";
  import FormElement from "../components/FormElement.svelte";

  type Props = WidgetProps<PasswordValidateOldData, PasswordValidateOldSettings>;

  let {
    component,
    theme,
    settings,
    value,
    onChange,
    name,
    id,
    attributes,
    labels,
  }: Props = $props();

  const classes = $derived(theme.classes);
  const confirmName = $derived(`${id}_confirm`);
  const confirmTitle = $derived(settings?.confirmTitle ?? "Confirm password");
  const oldPasswordLabel = $derived(settings?.oldPasswordLabel ?? "Old password");

  const oldPasswordValue = $derived(value?.oldPassword ?? "");
  const passwordValue = $derived(value?.password ?? "");
  const confirmPasswordValue = $derived(value?.confirmPassword ?? "");
  const matches = $derived(
    !!value &&
      value.password.length > 0 &&
      value.confirmPassword === value.password,
  );

  function changeOldPassword(e: Event) {
    const target = e.currentTarget as HTMLInputElement;
    onChange({
      oldPassword: target.value,
      password: value?.password ?? "",
      confirmPassword: value?.confirmPassword ?? "",
    });
  }

  function changePassword(e: Event) {
    const target = e.currentTarget as HTMLInputElement;
    onChange({
      oldPassword: value?.oldPassword ?? "",
      password: target.value,
      confirmPassword: value?.confirmPassword ?? "",
    });
  }

  function changeConfirmPassword(e: Event) {
    const target = e.currentTarget as HTMLInputElement;
    onChange({
      oldPassword: value?.oldPassword ?? "",
      password: value?.password ?? "",
      confirmPassword: target.value,
    });
  }
</script>

<div class={classes.componentWrapper}>
  <FormElement
    labelClass={classes.label}
    childrenClass={classes.elementWrapper}
    required={component.required}
    requiredText={labels?.required ?? "Required"}
    requiredClass={classes.requiredIndicator}
    labelWrapperClass={classes.labelWrapper}
    id={name}
    label={oldPasswordLabel}
  >
    <input
      type="password"
      class={classes.input}
      required={component.required || oldPasswordValue !== ""}
      value={oldPasswordValue}
      oninput={changeOldPassword}
      name={`${name}[oldpassword]`}
      id={`${id}_oldpassword`}
      {...attributes}
    />
  </FormElement>
</div>

<div class={classes.componentWrapper}>
  <FormElement
    labelClass={classes.label}
    childrenClass={classes.elementWrapper}
    required={component.required}
    requiredText={labels?.required ?? "Required"}
    requiredClass={classes.requiredIndicator}
    labelWrapperClass={classes.labelWrapper}
    id={id}
    label={component.label}
  >
    <input
      type="password"
      class={classes.input}
      required={component.required}
      value={passwordValue}
      oninput={changePassword}
      name={`${name}[password]`}
      {id}
      {...attributes}
    />
  </FormElement>
</div>

<div class={classes.componentWrapper}>
  <FormElement
    labelClass={classes.label}
    childrenClass={classes.elementWrapper}
    required={component.required}
    requiredText={labels?.required ?? "Required"}
    requiredClass={classes.requiredIndicator}
    labelWrapperClass={classes.labelWrapper}
    id={confirmName}
    label={confirmTitle}
  >
    <input
      type="password"
      class={classes.input}
      required={component.required}
      value={confirmPasswordValue}
      oninput={changeConfirmPassword}
      name={`${name}[confirmPassword]`}
      id={`${id}_confirm`}
      pattern={value ? `^${value.password}$` : undefined}
    />
    {#if matches}
      <div class={classes.descriptionOk}>The password matches!</div>
    {/if}
  </FormElement>
</div>
