// packages/core/src/types/text/TextArea.tsx
import * as React from "react";
import { WidgetProps } from "../../widget";
import FormComponentWrapper from "../../components/FormComponentWrapper";
/**
 * The text area widget allows you to render a textarea html element.
 * @group React widgets
 */
export default function TextArea(
  props: WidgetProps<string, unknown>,
): JSX.Element {
  const component = props.component;
  return (
    <FormComponentWrapper {...props}>
      <textarea
        className={props.theme.classes.textarea}
        required={component.required}
        value={props.value}
        disabled={component.disabled}
        onChange={(e) => props.onChange(e.currentTarget.value)}
        name={props.name}
        id={props.id}
        {...props.attributes}
      />
    </FormComponentWrapper>
  );
}

// packages/svelte/src/lib/widgets/TextArea.svelte
<script lang="ts">
  import type { WidgetProps } from "@fab4m/fab4m";
  import FormComponentWrapper from "../components/FormComponentWrapper.svelte";

  type Props = WidgetProps<string, unknown>;

  let { component, theme, value, onChange, name, id, attributes, hideLabel, labels }: Props = $props();
  let classes = $derived(theme.classes);
</script>

<FormComponentWrapper
  {component}
  {theme}
  {hideLabel}
  {labels}
  {name}
  {id}
  {attributes}
>
  <textarea
    class={classes.textarea}
    required={component.required}
    {value}
    disabled={component.disabled}
    oninput={(e) => onChange(e.currentTarget.value)}
    {name}
    {id}
    {...attributes}
  />
</FormComponentWrapper>
