// packages/svelte/src/lib/widgets/PasswordVerify.svelte
<script lang="ts">
  import type {
    PasswordSettings,
    PasswordVerifyData,
    WidgetProps,
  } from "@fab4m/fab4m";
  import FormComponentWrapper from "../components/FormComponentWrapper.svelte";

  type Props = WidgetProps<PasswordVerifyData, PasswordSettings>;

  let {
    component,
    theme,
    settings,
    value,
    onChange,
    name,
    id,
    attributes,
    hideLabel,
    labels,
  }: Props = $props();

  const classes = $derived(theme.classes);
  const confirmName = $derived(`${id}_confirm`);
  const confirmTitle = $derived(settings?.confirmTitle ?? "Confirm password");
  const passwordValue = $derived(value?.password ?? "");
  const confirmPasswordValue = $derived(value?.confirmPassword ?? "");
  const matches = $derived(
    !!value &&
      value.password.length > 0 &&
      value.confirmPassword === value.password,
  );

  function changePassword(e: Event) {
    const target = e.currentTarget as HTMLInputElement;
    onChange({
      password: target.value,
      confirmPassword: value?.confirmPassword ?? "",
    });
  }

  function changeConfirmPassword(e: Event) {
    const target = e.currentTarget as HTMLInputElement;
    onChange({
      password: value?.password ?? "",
      confirmPassword: target.value,
    });
  }
</script>

<div class={classes.componentWrapper}>
  <FormComponentWrapper
    {component}
    {theme}
    {hideLabel}
    {labels}
    {name}
    {id}
  >
    <input
      type="password"
      class={classes.input}
      required={component.required}
      value={passwordValue}
      oninput={changePassword}
      name={`${name}[password]`}
      {id}
      {...attributes}
    />
  </FormComponentWrapper>
</div>

<div class={classes.componentWrapper}>
  <FormComponentWrapper
    {component}
    {theme}
    {hideLabel}
    {labels}
    {name}
    id={confirmName}
    label={confirmTitle}
  >
    <input
      type="password"
      class={classes.input}
      required={component.required || passwordValue !== ""}
      value={confirmPasswordValue}
      oninput={changeConfirmPassword}
      name={`${name}[confirmPassword]`}
      id={`${id}-confirmPassword`}
      pattern={value ? `^${value.password}$` : undefined}
    />
    {#if matches}
      <div class={classes.descriptionOk}>The password matches!</div>
    {/if}
  </FormComponentWrapper>
</div>

// packages/password/src/PasswordVerify.tsx
import * as React from "react";
import { WidgetProps, FormComponentWrapper } from "@fab4m/fab4m";
import { PasswordSettings, PasswordVerifyData } from ".";
/**
 * The password Verify component renders a password input field
 * and a field to verify that password.
 * @group React widgets
 */
export default function PasswordVerify(
  props: WidgetProps<PasswordVerifyData, PasswordSettings>,
): JSX.Element {
  const component = props.component;
  const confirmName = `${props.id}_confirm`;
  const confirmTitle = props.settings.confirmTitle
    ? props.settings.confirmTitle
    : "Confirm password";

  return (
    <>
      <div className={props.theme.classes.componentWrapper}>
        <FormComponentWrapper {...props}>
          <input
            type="password"
            className={props.theme.classes.input}
            required={component.required}
            value={props.value?.password ?? ""}
            onChange={(e) =>
              props.onChange({
                ...value(props.value),
                password: e.currentTarget.value,
              })
            }
            name={`${props.name}[password]`}
            id={props.id}
            {...props.attributes}
          />
        </FormComponentWrapper>
      </div>
      <div className={props.theme.classes.componentWrapper}>
        <FormComponentWrapper {...props} id={confirmName} label={confirmTitle}>
          <input
            type="password"
            className={props.theme.classes.input}
            required={component.required || !!props.value?.password}
            value={props.value?.confirmPassword ?? ""}
            onChange={(e) =>
              props.onChange({
                ...value(props.value),
                confirmPassword: e.currentTarget.value,
              })
            }
            name={`${props.name}[confirmPassword]`}
            id={`${props.id}-confirmPassword`}
            pattern={props.value ? `^${props.value.password}$` : undefined}
          />
          {props.value &&
            props.value.password.length > 0 &&
            props.value.confirmPassword === props.value.password && (
              <div className={props.theme.classes.descriptionOk}>
                The password matches!
              </div>
            )}
        </FormComponentWrapper>
      </div>
    </>
  );
}
const defaultValue: PasswordVerifyData = {
  password: "",
  confirmPassword: "",
};
function value(val?: PasswordVerifyData) {
  return val ?? defaultValue;
}
