// fab4m.org/src/components/Guide/validators/MinLength.tsx
import React, { useState } from "react";
import {
  createForm,
  textField,
  minLength,
  StatefulFormView,
} from "@fab4m/fab4m";

const form = createForm({
  longtext: textField({
    label: "Long text (at least 10 characters)",
    validators: [minLength(10)],
  }),
});

export default function MinLengthExample() {
  const [longText, changeLongText] = useState(undefined);
  form.onSubmit((e, data) => {
    e.preventDefault();
    changeLongText(data.longtext);
  });
  return (
    <div>
      <StatefulFormView form={form} />
      {longText && (
        <div>
          <strong>Your long text:</strong> {longText}
        </div>
      )}
    </div>
  );
}

// fab4m.org-astro/src/components/examples/validators/MinLength.svelte
<script lang="ts">
  import { createForm, textField, minLength } from "@fab4m/fab4m";
  import {
    StatefulFormView,
    FormProvider,
    allWidgetsRenderer,
  } from "@fab4m/svelte";

  const form = createForm({
    longtext: textField({
      label: "Long text (at least 10 characters)",
      validators: [minLength(10)],
    }),
  });

  let longText = $state<string | undefined>(undefined);

  form.onSubmit((e, data) => {
    e.preventDefault();
    longText = data.longtext;
  });
</script>

<div>
  <FormProvider renderer={allWidgetsRenderer}>
    <StatefulFormView {form} />
  </FormProvider>
  {#if longText}
    <div>
      <strong>Your long text:</strong> {longText}
    </div>
  {/if}
</div>
