// packages/svelte/src/lib/components/FormProvider.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import {
     setFormRendererContext,
  } from "../formrenderer.js";
  import type { FormRenderer } from "../formrenderer.js";

  export type FormProviderProps = {
    renderer: FormRenderer;
    children: Snippet;
  };
  const { renderer, children }: FormProviderProps = $props();

  setFormRendererContext(renderer);
</script>

{@render children()}

// packages/react/src/components/FormProvider.tsx
import * as React from "react";
import {
  createFormRenderer,
  FormRendererContext,
  FormRenderer,
} from "../formrenderer";

export type FormProviderProps = {
  renderer: FormRenderer;
  children: React.ReactNode;
};

export function FormProvider(props: FormProviderProps) {
  const renderer = createFormRenderer(props.renderer);
  return (
    <FormRendererContext.Provider value={renderer}>
      {props.children}
    </FormRendererContext.Provider>
  );
}
