// packages/svelte/src/lib/components/FormElement.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  /**
   * @internal
   */
  let {
    id,
    label,
    required,
    requiredText,
    labelWrapperClass = "title-wrapper",
    childrenClass = "control",
    labelClass = "form-label",
    requiredClass = "required-indicator",
    children,
  }: {
    id: string;
    label?: string;
    required: boolean;
    requiredText: string;
    labelWrapperClass?: string;
    childrenClass?: string;
    labelClass?: string;
    requiredClass?: string;
    children: Snippet;
  } = $props();
</script>

<div class={labelWrapperClass}>
  {#if label}
    <label class={labelClass} for={id}>
      <span>{label}</span>
    </label>
  {/if}
  {#if label && required}
    <span class={requiredClass} aria-label={requiredText}>*</span>
  {/if}
</div>
<div class={childrenClass}>
  {@render children()}
</div>

// packages/react/src/components/FormElement.tsx
import * as React from "react";
/**
 * @internal
 */
export function FormElement({
  id,
  label,
  children,
  required,
  requiredText,
  labelWrapperClass = "title-wrapper",
  childrenClass = "control",
  labelClass = "form-label",
  requiredClass = "required-indicator",
}: {
  id: string;
  label?: string;
  children: React.ReactNode;
  labelClass?: string;
  required: boolean;
  requiredText: string;
  wrapperClass?: string;
  labelWrapperClass: string;
  childrenClass?: string;
  requiredClass?: string;
}): React.JSX.Element {
  return (
    <>
      <div className={labelWrapperClass}>
        {label && (
          <label className={labelClass} htmlFor={id}>
            <span>{label}</span>
          </label>
        )}
        {label && required && (
          <span className={requiredClass} aria-label={requiredText}>
            *
          </span>
        )}
      </div>
      <div className={childrenClass}>{children}</div>
    </>
  );
}
