// packages/svelte/src/lib/widgets/UploadField.svelte
<script lang="ts">
  import type { WidgetProps } from "@fab4m/fab4m";
  import FormComponentWrapper from "../components/FormComponentWrapper.svelte";

  type Props = WidgetProps<File, unknown | undefined>;

  let { component, theme, value, onChange, name, id, attributes, hideLabel, labels }: Props = $props();

  let classes = $derived(theme.classes);

  let changeFile = (e: Event) => {
    const target = e.target as HTMLInputElement;
    if (target.files && target.files.length > 0) {
      const file = target.files[0];
      onChange(file);
    }
  };
</script>

<FormComponentWrapper
  {component}
  {theme}
  {hideLabel}
  {labels}
  {name}
  {id}
  {attributes}
>
  <input
    type="file"
    class={classes.fileInput}
    disabled={component.disabled}
    required={component.required}
    onchange={changeFile}
    {name}
    {id}
    {...attributes}
  />
</FormComponentWrapper>

// packages/core/src/types/file/UploadField.tsx
import * as React from "react";
import FormComponentWrapper from "../../components/FormComponentWrapper";
import { WidgetProps } from "../../widget";
/**
 * A react component that renders an input with the type "file".
 * @group React widgets
 */
export default function UploadField(
  props: WidgetProps<File, unknown | undefined>,
): JSX.Element {
  const component = props.component;
  const classes = props.theme.classes;

  const changeFile = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      const file = e.target.files[0];
      props.onChange(file);
    }
  };
  return (
    <FormComponentWrapper {...props}>
      <input
        type="file"
        className={classes.fileInput}
        disabled={component.disabled}
        required={component.required}
        onChange={changeFile}
        name={props.name}
        id={props.id}
        {...props.attributes}
      />
    </FormComponentWrapper>
  );
}
