// packages/svelte/src/lib/widgets/multiple/Tags.svelte
<script lang="ts">
  import { type Component } from "svelte";
  import {
    findOption,
    isOptionGroup,
    optionValue,
  } from "@fab4m/fab4m";
  import type {
    MultipleWidgetProps,
    SelectWidgetSettings,
    TagsSettings,
  } from "@fab4m/fab4m";
  import FormComponentView from "../../components/FormComponentView.svelte";
  import ValidationErrors from "../../components/ValidationErrors.svelte";

  type Props<Value> = MultipleWidgetProps<Value, TagsSettings | undefined>;

  let { component, theme, settings, value, onChange, name, id, errors }: Props<string> = $props();

  let items = $derived(value ?? []);

  let defaultSettings: Required<TagsSettings> = {
    addItemLabel: settings?.addItemLabel ?? "Add",
    removeItemLabel: settings?.removeItemLabel ?? "Remove",
    addOnChange: settings?.addOnChange ?? false,
    itemAlreadyAddedMessage: settings?.itemAlreadyAddedMessage ?? "This item has already been added",
  };

  let draft = $state<string | undefined>(undefined);

  let addItem = (val: string) => onChange([...items, val]);

  let changeOrAdd = (data: unknown) => {
    draft = data as string | undefined;
    if (typeof data !== "undefined" && defaultSettings.addOnChange) {
      draft = undefined;
      addItem(data as string);
    }
  };

  let addButtonClicked = () => {
    const val = draft;
    if (typeof val !== "undefined") {
      draft = undefined;
      addItem(val);
    }
  };

  let itemExists = $derived(draft && items.findIndex((v) => v === draft) !== -1);

  let displayErrors = $derived.by(() => {
    const errs = errors ?? [];
    if (itemExists) {
      return [...errs, { path: "", message: defaultSettings.itemAlreadyAddedMessage }];
    }
    return errs;
  });

  let removeValue = (index: number) => {
    const newItems = [...items];
    newItems.splice(index, 1);
    onChange(newItems);
  };

  const getDisplayValue = (comp: { widget: { type: { name: string }; settings: any } }, val: string): string | number | undefined => {
    if (comp.widget.type.name !== "select") {
      return typeof val === "number" || typeof val === "string" ? val : undefined;
    }
    const selectSettings = comp.widget.settings as SelectWidgetSettings<string>;
    const option = findOption(selectSettings.options, val);
    if (!option) {
      return typeof val === "number" || typeof val === "string" ? val : undefined;
    }
    return Array.isArray(option) ? option[0] : (typeof option === "number" || typeof option === "string" ? option : undefined);
  };

  const alterComponent = (comp: any, values: string[] | undefined): any => {
    const alteredComponent = {
      ...comp,
      widget: {
        ...comp.widget,
        settings: { ...comp.widget.settings },
      },
      description: undefined,
      required: false,
    };
    if (comp.widget.type.name === "select" && values) {
      const newOptions = [];
      for (const option of comp.widget.settings.options) {
        if (!isOptionGroup(option) && values.findIndex((v) => v === optionValue(option)) === -1) {
          newOptions.push(option);
        }
      }
      alteredComponent.widget.settings.options = newOptions;
    }
    return alteredComponent;
  };
</script>

<div class={theme.classes.tags}>
  {#if component.label}
    <label class={theme.classes.label} for={id}>
      {component.label}
    </label>
  {/if}
  {#if items.length > 0}
    <div class={theme.classes.addedTags}>
      {#each items as itemValue, index}
        <div class={theme.classes.tag}>
          <div class={theme.classes.tagLabel}>{getDisplayValue(component, itemValue)}</div>
          {#if !component.disabled}
            <button
              class={theme.classes.removeTag}
              type="button"
              onclick={() => removeValue(index)}
            >
              {defaultSettings.removeItemLabel}
            </button>
          {/if}
        </div>
      {/each}
    </div>
  {/if}
  {#if !component.disabled && (!component.maxItems || component.maxItems > items.length)}
    <div class={theme.classes.addTagWrapper}>
      <FormComponentView
        value={draft}
        onChange={changeOrAdd}
        index={0}
        hideLabel={true}
        {name}
        {theme}
        component={alterComponent(component, items)}
      />
      {#if !defaultSettings.addOnChange}
        <button
          type="button"
          disabled={typeof draft === "undefined" || !!itemExists}
          onclick={addButtonClicked}
          id={`${id}-add`}
          class={theme.classes.addTag}
        >
          {defaultSettings.addItemLabel}
        </button>
      {/if}
    </div>
  {/if}
  {#if component.description}
    <div class={theme.classes.description}>
      {component.description}
    </div>
  {/if}
  {#if errors}
    <ValidationErrors errors={displayErrors} classes={theme.classes} />
  {/if}
</div>

// packages/react/src/widgets/multiple/Tags.tsx
import * as React from "react";
import { useState } from "react";
import {
  findOption,
  isOptionGroup,
  MultipleWidgetProps,
  optionValue,
  SelectWidgetSettings,
  TagsSettings,
} from "@fab4m/fab4m";
import { FormComponentView } from "../../components/FormComponentView";
import { ValidationErrors } from "../../components/ValidationErrors";
/**
 * The Tags react widget.
 * @group React multiple widgets
 */
export function Tags<Value>(
  props: MultipleWidgetProps<Value, TagsSettings | undefined>,
): React.JSX.Element | null {
  const addItem = (value: Value) => props.onChange([...items, value]);
  const items = props.value ?? [];
  const settings = allSettings(props.settings);
  const errors = props.errors ?? [];
  const [draft, changeDraft] = useState<Value | undefined>(undefined);
  const changeOrAdd = (data: unknown) => {
    changeDraft(data as Value | undefined);
    if (typeof data !== "undefined" && settings.addOnChange) {
      changeDraft(undefined);
      addItem(data as Value);
    }
  };
  const addButtonClicked = () => {
    if (typeof draft !== "undefined") {
      changeDraft(undefined);
      addItem(draft);
    }
  };
  const itemExists =
    draft && items.findIndex((value) => value === draft) !== -1;
  if (itemExists) {
    errors.push({ path: "", message: settings.itemAlreadyAddedMessage });
  }
  const itemComponents = items.map((value, index) => {
    const removeValue = () => {
      const newItems = [...items];
      newItems.splice(index, 1);
      props.onChange(newItems);
    };
    const displayValue = getDisplayValue(props.component, value);
    return (
      <div className={props.theme.classes.tag} key={index}>
        <div className={props.theme.classes.tagLabel}>{displayValue}</div>
        {!props.component.disabled && (
          <button
            className={props.theme.classes.removeTag}
            type="button"
            onClick={removeValue}
          >
            {settings.removeItemLabel}
          </button>
        )}
      </div>
    );
  });
  return (
    <div className={props.theme.classes.tags}>
      {props.component.label && (
        <label className={props.theme.classes.label} htmlFor={props.id}>
          {props.component.label}
        </label>
      )}
      {itemComponents.length > 0 && (
        <div className={props.theme.classes.addedTags}>{itemComponents}</div>
      )}
      {!props.component.disabled &&
        (!props.component.maxItems ||
          props.component.maxItems > items.length) && (
          <div className={props.theme.classes.addTagWrapper}>
            <FormComponentView
              value={draft}
              onChange={changeOrAdd}
              index={0}
              hideLabel={true}
              name={props.name}
              theme={props.theme}
              component={alterComponent(props.component, props.value)}
            />
            {!settings.addOnChange && (
              <button
                type="button"
                disabled={typeof draft === "undefined" || !!itemExists}
                onClick={addButtonClicked}
                id={`${props.id}-add`}
                className={props.theme.classes.addTag}
              >
                {settings.addItemLabel}
              </button>
            )}
          </div>
        )}
      {props.component.description && (
        <div className={props.theme.classes.description}>
          {props.component.description}
        </div>
      )}
      {props.errors && (
        <ValidationErrors errors={props.errors} classes={props.theme.classes} />
      )}
    </div>
  );
}

function getDisplayValue<Value>(
  component: {
    widget: { type: { name: string }; settings: any };
  },
  value: Value,
): string | number | React.ReactNode | undefined {
  const validValue = (valueToValidate: Value) =>
    typeof valueToValidate === "number" || typeof valueToValidate === "string"
      ? valueToValidate
      : undefined;
  if (component.widget.type.name !== "select") {
    return validValue(value);
  }
  const settings = component.widget.settings as SelectWidgetSettings<Value>;
  const option = findOption(settings.options, value);
  if (!option) {
    return validValue(value);
  }
  return Array.isArray(option) ? option[0] : validValue(option);
}

function alterComponent<Value>(
  component: any,
  values: Value[] | undefined,
): any {
  // We need to clone the relevant bits so that we don't break the
  // original objects.
  const alteredComponent = {
    ...component,
    widget: {
      ...component.widget,
      settings: { ...component.widget.settings },
    },
    description: undefined,
    required: false,
  };
  if (component.widget.type.name === "select" && values) {
    const newOptions = [];
    for (const option of component.widget.settings.options) {
      if (
        !isOptionGroup(option) &&
        values.findIndex((value) => value === optionValue(option)) === -1
      ) {
        newOptions.push(option);
      }
    }
    alteredComponent.widget.settings.options = newOptions;
  }
  return alteredComponent;
}

function allSettings(settings?: TagsSettings): Required<TagsSettings> {
  return {
    addItemLabel: settings?.addItemLabel ?? "Add",
    removeItemLabel: settings?.removeItemLabel ?? "Remove",
    addOnChange: settings?.addOnChange ?? false,
    itemAlreadyAddedMessage:
      settings?.itemAlreadyAddedMessage ?? "This item has already been added",
  };
}
