// packages/svelte/src/lib/widgets/NumberField.svelte
<script lang="ts">
  import type { NumberWidgetSettings, WidgetProps } from "@fab4m/fab4m";
  import FormComponentWrapper from "../components/FormComponentWrapper.svelte";

  type Props = WidgetProps<number, NumberWidgetSettings>;

  let { component, theme, settings, value, onChange, name, id, attributes, hideLabel, labels }: Props = $props();

  let classes = $derived(theme.classes);

  let convertValue = (val: string) => {
    return component.type.dataType === "float"
      ? parseFloat(val)
      : parseInt(val, 10);
  };

  let draft = $state<string | undefined>(value?.toString());

  $effect(() => {
    draft = value?.toString();
  });

  let changeValue = (e: Event) => {
    const target = e.target as HTMLInputElement;
    draft = target.value;
    const newValue = convertValue(target.value);
    if (!isNaN(newValue)) {
      onChange(newValue);
    }
  };
</script>

<FormComponentWrapper
  {component}
  {theme}
  {hideLabel}
  {labels}
  {name}
  {id}
  prefix={settings?.prefix}
>
  <input
    class={classes.input}
    required={component.required}
    value={draft ?? ""}
    disabled={component.disabled}
    oninput={changeValue}
    {name}
    {id}
    type="number"
    step={component.type.dataType === "float" ? "any" : undefined}
    {...attributes}
  />
</FormComponentWrapper>

// packages/react/src/widgets/NumberField.tsx
import * as React from "react";
import { ChangeEvent, useEffect, useState } from "react";
import { NumberWidgetSettings, WidgetProps } from "@fab4m/fab4m";
import { FormComponentWrapper } from "../components/FormComponentWrapper";

/**
 * The number field widget component renders a number input.
 * @group React widgets
 */
export function NumberField(
  props: WidgetProps<number, NumberWidgetSettings>,
): React.JSX.Element {
  const classes = props.theme.classes;
  const component = props.component;
  const convertValue = (value: string) => {
    return component.type.dataType === "float"
      ? parseFloat(value)
      : parseInt(value, 10);
  };
  const [draft, changeDraft] = useState<string | undefined>(
    props.value?.toString(),
  );

  useEffect(() => {
    changeDraft(props.value?.toString());
  }, [props.value]);

  const changeValue = (e: ChangeEvent<HTMLInputElement>) => {
    changeDraft(e.target.value);
    const value = convertValue(e.target.value);
    if (!isNaN(value)) {
      props.onChange(value);
    }
  };

  return (
    <FormComponentWrapper {...props} prefix={props.settings.prefix}>
      <input
        className={classes.input}
        required={component.required}
        value={draft ?? ""}
        disabled={component.disabled}
        onChange={changeValue}
        name={props.name}
        id={props.id}
        type="number"
        step={props.component.type.dataType === "float" ? "any" : undefined}
        {...props.attributes}
      />
    </FormComponentWrapper>
  );
}
