// packages/svelte/src/lib/widgets/Radios.svelte
<script lang="ts">
  import { optionValue } from "@fab4m/fab4m";
  import type { Option, WidgetProps } from "@fab4m/fab4m";
  import FormComponentWrapper from "../components/FormComponentWrapper.svelte";

  type Props<OptionsType extends string | number = string | number> = WidgetProps<OptionsType, Option<OptionsType>[]>;

  let { component, theme, settings, value, onChange, name, id, attributes, hideLabel, labels }: Props = $props();

  let classes = $derived(theme.classes);
</script>

<FormComponentWrapper
  {component}
  {theme}
  {hideLabel}
  {labels}
  {name}
  {id}
  {attributes}
>
  <div class={classes.radiosWrapper}>
    {#each settings as option, index}
      {@const optionId = `${id}-${index}`}
      {@const optionVal = optionValue(option) as Props["value"]}
      {@const elementValue = typeof optionVal === "string" || typeof optionVal === "number" ? optionVal : undefined}
      <label class={classes.radioWrapper} for={optionId}>
        <input
          type="radio"
          id={optionId}
          {name}
          value={elementValue}
          onchange={() => onChange(optionVal)}
          checked={value === optionVal}
        />
        {Array.isArray(option) ? option[0] : option}
      </label>
    {/each}
  </div>
</FormComponentWrapper>

// packages/react/src/widgets/Radios.tsx
import * as React from "react";
import FormComponentWrapper from "../components/FormComponentWrapper";
import { WidgetProps } from "../widget";
import { Option, optionValue } from "./options";
/**
 * The Radios widget renders a series of radio input widget for each option.
 * @group React widgets
 */
function Radios<OptionsType extends string | number | React.ReactElement>(
  props: WidgetProps<OptionsType, Option<OptionsType>[]>,
) {
  const classes = props.theme.classes;
  const options = props.settings.map((option, index) => {
    const id = `${props.id}-${index}`;
    const value = optionValue(option);
    let elementValue: string | number | undefined;
    if (typeof value === "string" || typeof value === "number") {
      elementValue = value;
    }
    return (
      <label className={classes.radioWrapper} htmlFor={id} key={index}>
        <>
          <input
            type="radio"
            id={id}
            name={props.name}
            value={elementValue}
            onChange={() => props.onChange(value)}
            checked={props.value === value}
          />{" "}
          {Array.isArray(option) ? option[0] : option}
        </>
      </label>
    );
  });
  return (
    <FormComponentWrapper {...props}>
      <div className={classes.radiosWrapper}>{options}</div>
    </FormComponentWrapper>
  );
}

export default Radios as React.FC;
