// packages/svelte/src/lib/widgets/Select.svelte
<script lang="ts">
  import {
    isOptionGroup,
    optionValue,
  } from "@fab4m/fab4m";
  import type {
    Option,
    OptionGroup,
    SelectWidgetSettings,
    WidgetProps,
  } from "@fab4m/fab4m";
  import FormComponentWrapper from "../components/FormComponentWrapper.svelte";

  type OptionValue = string | number;
  type Props<OptionsType extends OptionValue = OptionValue> = WidgetProps<OptionsType, SelectWidgetSettings<OptionsType>>;

  let { component, theme, settings, value, onChange, name, id, attributes, hideLabel, labels }: Props = $props();

  let classes = $derived(theme.classes);

  let change = (e: Event) => {
    const target = e.target as HTMLSelectElement;
    let newValue: OptionValue;
    switch (component.type.dataType) {
      case "integer":
        newValue = parseInt(target.value, 10);
        break;
      case "float":
        newValue = parseFloat(target.value);
        break;
      default:
        newValue = target.value;
    }
    onChange(newValue as Props["value"]);
  };
</script>

<FormComponentWrapper
  {component}
  {theme}
  {hideLabel}
  {labels}
  {name}
  {id}
  {attributes}
>
  <div class={theme.classes.selectWrapper}>
    <select
      class={classes.select}
      value={typeof value === "undefined" ? "" : value}
      {id}
      {name}
      required={component.required}
      disabled={component.disabled}
      onchange={change}
      {...attributes}
    >
      <option value="">
        {settings.notSelectedLabel ?? "- Select -"}
      </option>
      {#each settings.options as option, index}
        {#if isOptionGroup(option)}
          <optgroup label={option[0]}>
            {#each option[1] as childOption, childIndex}
              {@const opt = childOption as Option<OptionValue>}
              <option value={optionValue(opt)}>
                {Array.isArray(opt) ? opt[0] : opt}
              </option>
            {/each}
          </optgroup>
        {:else}
          <option value={optionValue(option)}>
            {Array.isArray(option) ? option[0] : option}
          </option>
        {/if}
      {/each}
    </select>
  </div>
</FormComponentWrapper>

// packages/react/src/widgets/Select.tsx
import * as React from "react";
import {
  Option,
  OptionGroup,
  SelectWidgetSettings,
  isOptionGroup,
  optionValue,
  WidgetProps,
} from "@fab4m/fab4m";
import { FormComponentWrapper } from "../components/FormComponentWrapper";

type OptionValue = string | number;

function renderOption<OptionsType extends OptionValue>(
  option: Option<OptionsType> | OptionGroup<OptionsType>,
  index: number,
): React.JSX.Element {
  return isOptionGroup(option) ? (
    <optgroup key={index} label={option[0]}>
      {option[1].map((childOption, childIndex) =>
        renderOption(childOption, childIndex),
      )}
    </optgroup>
  ) : (
    <option key={index} value={optionValue(option)}>
      {Array.isArray(option) ? option[0] : option}
    </option>
  );
}
/**
 * Renders a select html element with the options provided.
 * @group React widgets
 */
export function Select<OptionsType extends OptionValue>(
  props: WidgetProps<OptionsType, SelectWidgetSettings<OptionsType>>,
): React.JSX.Element {
  const classes = props.theme.classes;
  const options = props.settings.options.map((option, index) =>
    renderOption(option, index),
  );
  const change = (e: React.ChangeEvent<HTMLSelectElement>) => {
    let value: OptionsType;
    switch (props.component.type.dataType) {
      case "integer":
        value = parseInt(e.target.value, 10) as OptionsType;
        break;
      case "float":
        value = parseFloat(e.target.value) as OptionsType;
        break;
      default:
        value = e.target.value as OptionsType;
    }
    props.onChange(value);
  };
  return (
    <FormComponentWrapper {...props}>
      <div className={props.theme.classes.selectWrapper}>
        <select
          className={classes.select}
          value={typeof props.value === "undefined" ? "" : props.value}
          id={props.id}
          name={props.name}
          required={props.component.required}
          disabled={props.component.disabled}
          onChange={change}
          {...props.attributes}
        >
          <option value="">
            {props.settings.notSelectedLabel ?? "- Select -"}
          </option>
          {options}
        </select>
      </div>
    </FormComponentWrapper>
  );
}
