// fab4m.org-astro/src/components/examples/components/DateRangeField.svelte
<script lang="ts">
  import { createForm, dateRangeField } from "@fab4m/fab4m";
  import {
    StatefulFormView,
    FormProvider,
    allWidgetsRenderer,
  } from "@fab4m/svelte";

  const form = createForm({
    vacation: dateRangeField({
      label: "Enter your desired vacation",
    }),
  });

  let result: { vacation?: { from: Date; to?: Date } } | null = null;
  form.onSubmit((e, data) => {
    e.preventDefault();
    result = data;
  });
</script>

<FormProvider renderer={allWidgetsRenderer}>
  <StatefulFormView {form} />
</FormProvider>

{#if result}
  <p>
    Your vacation is {result.vacation?.from.toLocaleDateString()} -{" "}
    {result.vacation?.to.toLocaleDateString()}
  </p>
{/if}

// fab4m.org-astro/src/components/examples/components/DateRangeField.tsx
import * as React from "react";
import { createForm, dateRangeField } from "@fab4m/fab4m";
import {
  StatefulFormView,
  FormProvider,
  allWidgetsRenderer,
} from "@fab4m/react";

const form = createForm({
  vacation: dateRangeField({
    label: "Enter your desired vacation",
  }),
});

export default function DateRangeField() {
  const [result, changeResult] = React.useState(null);
  form.onSubmit((e, data) => {
    e.preventDefault();
    changeResult(data);
  });
  return (
    <div>
      <FormProvider renderer={allWidgetsRenderer}>
        <StatefulFormView form={form} />
      </FormProvider>
      {result && (
        <p>
          Your vacation is {result.vacation?.from.toLocaleDateString()} -{" "}
          {result.vacation?.to.toLocaleDateString()}
        </p>
      )}
    </div>
  );
}
