// packages/react/src/widgets/Details.tsx
import * as React from "react";
import { DetailsSettings, WidgetProps } from "@fab4m/fab4m";
import { GroupChildren } from "./GroupChildren";

/**
 * Render a details widget with the group of fields.
 * The summary part can either be a string or any phrasing html content
 * in the form of react components.
 * @group React widgets
 */
export function Details<DataType = Record<string, any>>(
  props: WidgetProps<DataType, DetailsSettings<DataType>>,
): React.JSX.Element | null {
  if (!props.component.components) {
    return null;
  }
  let summary: string | undefined | React.ReactNode = props.component.label;
  if (props.settings.summary) {
    summary =
      typeof props.settings.summary === "function"
        ? props.settings.summary(props.value)
        : props.settings.summary;
  }
  return (
    <details
      open={props.settings.open}
      id={props.id}
      className={props.theme.classes.details}
    >
      <summary className={props.theme.classes.summary}>{summary}</summary>
      <div className={props.theme.classes.detailsContent}>
        <GroupChildren {...(props as WidgetProps<unknown, unknown>)} />
      </div>
    </details>
  );
}

// packages/svelte/src/widgets/Details.svelte
<script lang="ts">
  import { DetailsSettings, WidgetProps } from "@fab4m/fab4m";
  import { GroupChildren } from "./GroupChildren";
  /**
   * Render a details widget with the group of fields.
   * The summary part can either be a string or any phrasing html content
   * in the form of react components.
   * @group React widgets
   */
  let props: WidgetProps<any, DetailsSettings<any>> = $props();
  let summary = $derived.by(() => {
    if (props.settings.summary) {
      return typeof props.settings.summary === "function"
        ? props.settings.summary(props.value)
        : props.settings.summary;
    }
    return props.component.label;
  });
</script>
{#if props.component.components}
<details
  open={props.settings.open}
  id={props.id}
  class={props.theme.classes.details}
>
  <summary class={props.theme.classes.summary}>{summary}</summary>
  <div class={props.theme.classes.detailsContent}>
    <GroupChildren {...props} />
  </div>
</details>
{/if}
